name: documentation
on:
  push:
    branches: [ master ]

jobs:
  document:
    runs-on: ubuntu-latest

    env:
      RUSTDOCFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v2

      - name: Generate Documentation
        run: cargo doc --no-deps --verbose

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc